name: Code Quality Checks

on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: [ main, development ]

jobs:
  formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Tools Dependencies
      run: |
        pip install -r code_tools/requirements.txt
    
    - name: Run Black
      run: |
        chmod +x code_tools/black/check.sh
        ./code_tools/black/check.sh
    
    - name: Run isort
      run: |
        chmod +x code_tools/isort/check.sh
        ./code_tools/isort/check.sh
    
    - name: Run sort-all
      run: |
        chmod +x code_tools/sort_all/fix.sh
        ./code_tools/sort_all/fix.sh --check

  linting:
    name: Code Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Project Dependencies
      run: |
        pip install -e .
    
    - name: Install Tools Dependencies
      run: |
        pip install -r code_tools/requirements.txt
    
    - name: Run Pyflakes
      run: |
        chmod +x code_tools/pyflakes/check.sh
        ./code_tools/pyflakes/check.sh
    
    - name: Run Pydocstyle
      run: |
        chmod +x code_tools/pydocstyle/check.sh
        ./code_tools/pydocstyle/check.sh
    
    - name: Run Darglint
      run: |
        chmod +x code_tools/darglint/check.sh
        ./code_tools/darglint/check.sh
