name: Type Checking

on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: [ main, development ]

jobs:
  mypy:
    name: MyPy Type Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Project Dependencies
      run: |
        pip install -e .
    
    - name: Install MyPy
      run: |
        pip install -r codetools/mypy/requirements.txt
    
    - name: Run MyPy
      run: |
        chmod +x codetools/mypy/check_all.sh
        ./codetools/mypy/check_all.sh
